---
title: Stories Bookshop + Storytelling Lab
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Stories is a children's bookshop and storytelling lab in Brooklyn.
baseurl: 
url: https://storiesbk.com
repository: storiesbk/storiesbk.github.io
future: true
plugins:
- jekyll-sitemap
- jekyll-github-metadata
footer_openhours_text: Stories is closed until further notice due to Covid-19. Please
  support us by placing an online order [here](http://shop.storiesbk.com).
