title: "Stories Bookshop + Storytelling Lab"
description: "Stories is a children's bookshop and storytelling lab in Brooklyn."
baseurl: ""
url: "http://storiesbk.com/"
future: true
timezone: America/New_York
gems:
  - jekyll-sitemap
