title: "Stories Bookshop + Storytelling Lab"
description: "Stories is a children's bookshop and storytelling lab in Brooklyn."
baseurl: ""
url: "https://storiesbk.com/"
repository: storiesbk/storiesbk.github.io
future: true
timezone: America/New_York
plugins:
  - "jekyll-sitemap"
  - "jekyll-github-metadata"
